// Constants for creating advertisements
export const CREATE_ADVERTISEMENT_REQUEST = 'CREATE_ADVERTISEMENT_REQUEST';
export const CREATE_ADVERTISEMENT_SUCCESS = 'CREATE_ADVERTISEMENT_SUCCESS';
export const CREATE_ADVERTISEMENT_FAILURE = 'CREATE_ADVERTISEMENT_FAILURE';

// Constants for deleting advertisements
export const DELETE_ADVERTISEMENT_REQUEST = 'DELETE_ADVERTISEMENT_REQUEST';
export const DELETE_ADVERTISEMENT_SUCCESS = 'DELETE_ADVERTISEMENT_SUCCESS';
export const DELETE_ADVERTISEMENT_FAILURE = 'DELETE_ADVERTISEMENT_FAILURE';


// Constants for restaurant advertisements
export const GET_RESTAURANT_ADVERTISEMENTS_REQUEST = 'GET_RESTAURANT_ADVERTISEMENTS_REQUEST';
export const GET_RESTAURANT_ADVERTISEMENTS_SUCCESS = 'GET_RESTAURANT_ADVERTISEMENTS_SUCCESS';
export const GET_RESTAURANT_ADVERTISEMENTS_FAILURE = 'GET_RESTAURANT_ADVERTISEMENTS_FAILURE';

// Constants for cafe advertisements
export const GET_CAFE_ADVERTISEMENTS_REQUEST = 'GET_CAFE_ADVERTISEMENTS_REQUEST';
export const GET_CAFE_ADVERTISEMENTS_SUCCESS = 'GET_CAFE_ADVERTISEMENTS_SUCCESS';
export const GET_CAFE_ADVERTISEMENTS_FAILURE = 'GET_CAFE_ADVERTISEMENTS_FAILURE';
