export const CREATE_CAFE_REQUEST = 'CREATE_CAFE_REQUEST';
export const CREATE_CAFE_SUCCESS = 'CREATE_CAFE_SUCCESS';
export const CREATE_CAFE_FAILURE = 'CREATE_CAFE_FAILURE';

export const GET_ALL_CAFES_REQUEST = 'GET_ALL_CAFES_REQUEST';
export const GET_ALL_CAFES_SUCCESS = 'GET_ALL_CAFES_SUCCESS';
export const GET_ALL_CAFES_FAILURE = 'GET_ALL_CAFES_FAILURE';

export const GET_CAFE_BY_ID_REQUEST = 'GET_CAFE_BY_ID_REQUEST';
export const GET_CAFE_BY_ID_SUCCESS = 'GET_CAFE_BY_ID_SUCCESS';
export const GET_CAFE_BY_ID_FAILURE = 'GET_CAFE_BY_ID_FAILURE';

export const UPDATE_CAFE_REQUEST = 'UPDATE_CAFE_REQUEST';
export const UPDATE_CAFE_SUCCESS = 'UPDATE_CAFE_SUCCESS';
export const UPDATE_CAFE_FAILURE = 'UPDATE_CAFE_FAILURE';

export const DELETE_CAFE_REQUEST = 'DELETE_CAFE_REQUEST';
export const DELETE_CAFE_SUCCESS = 'DELETE_CAFE_SUCCESS';
export const DELETE_CAFE_FAILURE = 'DELETE_CAFE_FAILURE';

export const FILTER_ITEMS_CAFE_REQUEST = 'FILTER_ITEMS_CAFE_REQUEST';
export const FILTER_ITEMS_CAFE_SUCCESS = 'FILTER_ITEMS_CAFE_SUCCESS';
export const FILTER_ITEMS_CAFE_FAILURE = 'FILTER_ITEMS_CAFE_FAILURE';
