// userConstants.js

export const SAVE_USER_DATA_REQUEST = 'SAVE_USER_DATA_REQUEST';
export const SAVE_USER_DATA_SUCCESS = 'SAVE_USER_DATA_SUCCESS';
export const SAVE_USER_DATA_FAILURE = 'SAVE_USER_DATA_FAILURE';
