export const FILTER_LOCATIONS_REQUEST = 'FILTER_LOCATIONS_REQUEST';
export const FILTER_LOCATIONS_SUCCESS = 'FILTER_LOCATIONS_SUCCESS';
export const FILTER_LOCATIONS_FAILURE = 'FILTER_LOCATIONS_FAILURE';


// mapConstants.js
export const OPEN_GOOGLE_MAPS_REQUEST = 'OPEN_GOOGLE_MAPS_REQUEST';
export const OPEN_GOOGLE_MAPS_SUCCESS = 'OPEN_GOOGLE_MAPS_SUCCESS';
export const OPEN_GOOGLE_MAPS_FAILURE = 'OPEN_GOOGLE_MAPS_FAILURE';


//followerconstants
// followConstants.js
export const FOLLOW_REQUEST = 'FOLLOW_REQUEST';
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const FOLLOW_FAIL = 'FOLLOW_FAIL';

//search filter
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

//following  list
// actionTypes.js

export const FETCH_FOLLOWING_REQUEST = 'FETCH_FOLLOWING_REQUEST';
export const FETCH_FOLLOWING_SUCCESS = 'FETCH_FOLLOWING_SUCCESS';
export const FETCH_FOLLOWING_FAIL = 'FETCH_FOLLOWING_FAIL';
